#!/usr/bin/env ruby

# Trap ^C
Signal.trap("INT") {
  puts "\nCtrl-C detected. Exiting..."
  sleep 0.1
  exit
}

$:.unshift(File.expand_path("../../lib", __FILE__))
require "pipedream"
require "pipedream/cli"

Pipedream::CLI.start(ARGV)
